use std::env;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    // Embed Supabase URL and anon key from cliptool/.env.local so the packaged app
    // can sync license even when the frontend bundle has no env inlined.
    let out_dir = env::var("OUT_DIR").unwrap();
    let embed_path = Path::new(&out_dir).join("supabase_embed.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let env_path = Path::new(&manifest_dir)
        .join("../../cliptool/.env.local");

    let (url, key) = if env_path.exists() {
        let content = fs::read_to_string(&env_path).unwrap_or_default();
        let mut url = String::new();
        let mut key = String::new();
        for line in content.lines() {
            let line = line.trim();
            if line.starts_with("NEXT_PUBLIC_SUPABASE_URL=") {
                url = line
                    .strip_prefix("NEXT_PUBLIC_SUPABASE_URL=")
                    .unwrap_or("")
                    .trim_matches('"')
                    .to_string();
            } else if line.starts_with("NEXT_PUBLIC_SUPABASE_ANON_KEY=") {
                key = line
                    .strip_prefix("NEXT_PUBLIC_SUPABASE_ANON_KEY=")
                    .unwrap_or("")
                    .trim_matches('"')
                    .to_string();
            }
        }
        (url, key)
    } else {
        (String::new(), String::new())
    };

    let content = format!(
        r#"// Generated by build.rs - do not edit
pub const SUPABASE_URL_EMBED: &str = {:?};
pub const SUPABASE_ANON_KEY_EMBED: &str = {:?};
"#,
        url,
        key
    );
    fs::write(&embed_path, content).expect("write supabase_embed.rs");
}
